# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

blank_issues_enabled: false
contact_links:
  - name: Terraform Language Features / Bugs
    url: https://github.com/hashicorp/terraform-ls/issues
    about: >-
      Most of the language features of the VS Code extension are supplied by the Terraform
      Language Server. Issues with language features in many cases may need to be filed on
      that repository.
  - name: Discussion and Questions
    url: https://github.com/gamunu/vscode-opentofu/discussions
    about: Please use the OpenTofu extension Github discussions for questions and discussions.
