---
name: Run tests

on:
  push:
    branches:
      - main
      - pre-release
    paths-ignore:
      - 'syntaxes/**'
      - 'tests/**'
      - '**.md'
  pull_request:
    branches:
      - main
      - pre-release
    paths-ignore:
      - 'syntaxes/**'
      - 'tests/**'
      - '**.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version-file: '.nvmrc'
          cache: npm
      - name: npm install
        run: npm ci
      - name: lint
        run: npm run lint
      - name: format
        run: npm run check-format

  test:
    strategy:
      fail-fast: false
      matrix:
        vscode:
          - '1.88.0'
          - 'insiders'
          - 'stable'
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version-file: '.nvmrc'
      - name: Set up Xvfb (Ubuntu)
        run: |
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          echo ">>> Started xvfb"
        if: matrix.os == 'ubuntu-latest'
      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_wrapper: false
          tofu_version: 1.8.0
      - name: Tofu version
        run: tofu version
      - name: Clean Install Dependencies
        run: npm ci
      - name: Run Tests
        run: xvfb-run -a npm test
        if: runner.os == 'Linux'
      - name: Run Tests
        run: npm test
        if: runner.os != 'Linux'
