---
name: Run tests

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'syntaxes/**'
      - 'tests/**'
      - '**.md'
  pull_request:
    branches:
      - main
      - f-tfc
    paths-ignore:
      - 'syntaxes/**'
      - 'tests/**'
      - '**.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout Repo
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version-file: '.nvmrc'
      - name: npm install
        run: npm ci
      - name: lint
        run: npm run lint
      - name: format
        run: npm run check-format

  unit:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 3
    steps:
      - name: Checkout Repo
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version-file: '.nvmrc'
      - name: npm install
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install chromium
      - name: web unit
        run: npm run test:unit:web

  test:
    strategy:
      fail-fast: false
      matrix:
        vscode:
          - '1.88.0'
          - 'insiders'
          - 'stable'
        os:
          - windows-latest
          - macos-latest
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - name: Checkout Repo
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version-file: '.nvmrc'
      - name: Set up Xvfb (Ubuntu)
        run: |
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          echo ">>> Started xvfb"
        if: matrix.os == 'ubuntu-latest'
      - name: Install OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_wrapper: false
          tofu_version: 1.7.0
      - name: Tofu version
        run: tofu version
      - name: Clean Install Dependencies
        run: npm ci
      - name: Run Tests
        run: npm test
        env:
          CI: true
          DISPLAY: ':99.0'
          VSCODE_VERSION: ${{ matrix.vscode }}
